name: Build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v5
        with:
          cache: true
          go-version-file: go.mod

      - name: Build
        run: make build-linux

      - name: Setup gotestsum
        uses: autero1/action-gotestsum@v2.0.0
        with:
          gotestsum_version: 1.8.1

      - name: Test
        run: make test

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v1.60
